### ISSUE TITLE
Add your credential in coder.json [MANDATORY]

### ISSUE THREAD

**Issue by Himanshu276330** [opencodeiiita/Code-Digger#1]
## Submission Guideline

- Maintain Json Format to add your data. 

Hint : [To learn Json](https://www.javatpoint.com/json-tutorial)

**Comment by PiyushGG18** [comment]
Claim

**Comment by Himanshu276330** [comment]
This is open to all issues.
You don't need to claim it.

Just read the contributing guidelines step and do it.
