### ISSUE TITLE
Task 10: Sanyam and Primes

### ISSUE THREAD

**Issue by pvtr03** [opencodeiiita/Code-Digger#122]
## Steps to solve this problem successfully
- Solve the problem and create a new file `output.txt` in the same task folder
- Store the output in `output.txt`
- Also attach a file containing your code
- Submit a PR within 1 day
- Your PR will not be merged if it contains Wrong Answer

If you need any help regarding this issue, contact @hdelic#6900 on discord

**Comment by RibhavBansal** [comment]
claim

**Comment by ananyaa07** [comment]
claim

**Comment by terminatorXbgmi** [comment]
Claim

**Comment by pvtr03** [comment]
Assigned to @RibhavBansal

**Comment by pvtr03** [comment]
@RibhavBansal what's your progress on this issue?

**Comment by RibhavBansal** [comment]
Working on it.

**Comment by akshatsgh** [comment]
claim

**Comment by pvtr03** [comment]
This issue if open for claims again!

**Comment by SanyamAgrawal07** [comment]
claim

**Comment by Ayashika** [comment]
Claim

**Comment by TheDivineAurora** [comment]
claim

**Comment by pvtr03** [comment]
Assigned to @SanyamAgrawal07

**Comment by Himanshu276330** [comment]
This issue if open for claims again!

**Comment by TheDivineAurora** [comment]
claim

**Comment by Himanshu276330** [comment]
@TheDivineAurora go ahead and solve the task.
Best of luck.

**Comment by Himanshu276330** [comment]
@TheDivineAurora bro you have already 3 tasks assigned.

**Comment by pvtr03** [comment]
The issue is up for claims!

**Comment by TheDivineAurora** [comment]
claim

**Comment by pvtr03** [comment]
Assigned to @TheDivineAurora

**Comment by akshayw1** [comment]
Claim

**Comment by pvtr03** [comment]
Assigned to @akshayw1

**Comment by addygupta21** [comment]
claim

**Comment by pvtr03** [comment]
Open for claims, again!

**Comment by rakim-0** [comment]
claim

**Comment by 88oo** [comment]
claim

**Comment by pvtr03** [comment]
Assigned to @Koshal7

**Comment by sushantk1274** [comment]
claim

**Comment by pvtr03** [comment]
@Koshal7 was provided 20 points for partial correct answer.

The issue is open for claims, again!!

**Comment by akshatsgh** [comment]
claim

**Comment by pvtr03** [comment]
Assigned to @akshatsgh

**Comment by pvtr03** [comment]
This issue is open for claims again!
