### ISSUE TITLE
Editorial Task 2

### ISSUE THREAD

**Issue by pvtr03** [opencodeiiita/Code-Digger#137]
## Steps to resolve this issue successfully
- Make an editorial for `task-2-among-sus`.
- Add the editorial to the editorials folder.
- [Hint] See the editorial of task-1.
- The editorial should be simple and explanatory.
- You must submit a PR in 1 day.

If you need any help regarding this issue, contact @hdelic#6900 on discord

**Comment by Vishesh-Vijay** [comment]
Claim

**Comment by pvtr03** [comment]
Assigned to @Vishesh-Vijay
