### ISSUE TITLE
Editorial: Task 3 and 6

### ISSUE THREAD

**Issue by pvtr03** [opencodeiiita/Code-Digger#139]
## Steps to resolve this issue successfully
- Make an editorial for `task-6-bada-badmaash`.
- Add the editorial to the editorials folder.
- You may use the solution code of `task6`
- [Hint] See the editorial of task-1.
- The editorial should be simple and explanatory.
- You must submit a PR in 1 day.

If you need any help regarding this issue, contact @hdelic#6900 on discord

**Comment by ananyaa07** [comment]
claim

**Comment by pvtr03** [comment]
Assigned to @ananyaa07

**Comment by addygupta21** [comment]
claim
