### ISSUE TITLE
Task 14: Beautiful Number

### ISSUE THREAD

**Issue by pvtr03** [opencodeiiita/Code-Digger#144]
This is an open for all task, you do not need to claim it.

Fill in any 5 blank lines in the `output.txt` according to the problem statement in the `task14`. If any previous PR has filled the blanks before yours, then it will be rejected and you will have to make a new PR.

Do not disclose the code to anyone.
**Note**: The output should be in ascending order
If the number is say `ith` beautiful number, you have to output the number on the `ith` line only

If you need any help regarding this issue, contact hdelic#6900 on discord

**Comment by Latanshu14** [comment]
Claim

**Comment by sushantk1274** [comment]
claim
