### ISSUE TITLE
Editorial: Task 4

### ISSUE THREAD

**Issue by pvtr03** [opencodeiiita/Code-Digger#146]
## Steps to resolve this issue successfully
- Make an editorial for `task-4-among-sussier`.
- Add the editorial to the editorials folder.
- You may use the solution code of `task4`
- [Hint] See the editorial of task-1.
- The editorial should be simple and explanatory.
- You must submit a PR in 1 day.

If you need any help regarding this issue, contact hdelic#6900 on discord

**Comment by akshatsgh** [comment]
Claim

**Comment by pvtr03** [comment]
Assigned to @akshatsgh

**Comment by sushantk1274** [comment]
Claim

**Comment by pvtr03** [comment]
Assigned to @sushantk1274

**Comment by pvtr03** [comment]
@sushantk1274 what's your progress on this task

**Comment by JahnaviGadde** [comment]
claim

**Comment by TheDivineAurora** [comment]
claim

**Comment by pvtr03** [comment]
Assigned to @JahnaviGadde

**Comment by ananyaa07** [comment]
claim

**Comment by pvtr03** [comment]
Assigned to @ananyaa07
