### ISSUE TITLE
Task 3: Chota Badmaash

### ISSUE THREAD

**Issue by pvtr03** [opencodeiiita/Code-Digger#19]
## Steps to solve this problem successfully
- Solve the problem and create a new file `output.txt in` the same task folder
- Store the output in `output.txt`
- Also attach a file containing your code
- Submit a PR within 1 day
- Your PR will not be merged if it contains Wrong Answer

If you need any help regarding this issue, contact @hdelic#6900 on discord

**Comment by SanyamAgrawal07** [comment]
claim

**Comment by pvtr03** [comment]
Assigned to @SanyamAgrawal07

**Comment by RibhavBansal** [comment]
claim

**Comment by PiyushGG18** [comment]
CLAIM

**Comment by Kartikeyy-singh** [comment]
claim
