### ISSUE TITLE
Task 1: Pattern Finding

### ISSUE THREAD

**Issue by Himanshu276330** [opencodeiiita/Code-Digger#2]
## Steps to solve this problem successfully

- Solve the problem and create a new file `output.txt` in the same task folder.
- Store the output in `output.txt`.
- Also attach a file (.cpp or any programming code) containing your code.
- 
- You have 1 day until the spy gets bored with you and assigns the task to someone else.
- Your PR will not be merged if it contains the Wrong Answer.

**Comment by anshgeez31** [comment]
claim

**Comment by pvtr03** [comment]
Assigned to @anshgeez31

**Comment by Himanshu276330** [comment]
Best of luck @anshgeez31 
If you have any questions, feel free to ask on discord.

**Comment by Aman1143** [comment]
claim

**Comment by PiyushGG18** [comment]
claim

**Comment by Phantom-Harsh** [comment]
Claim

**Comment by RibhavBansal** [comment]
Claim
