### ISSUE TITLE
Editorial: Task 7

### ISSUE THREAD

**Issue by pvtr03** [opencodeiiita/Code-Digger#202]
## Steps to resolve this issue successfully
- Make an editorial for `task-7-among-sussiest`.
- Add the editorial to the editorials folder.
- You may use the solution code of `task-7`
- [Hint] See the editorial of task-1.
- The editorial should be simple and explanatory.
- You must submit a PR in 1 day.

If you need any help regarding this issue, contact hdelic#6900 on discord

**Comment by 88oo** [comment]
claim

**Comment by akshatsgh** [comment]
claim
