### ISSUE TITLE
Solve Task 2: Among Sus

### ISSUE THREAD

**Issue by pvtr03** [opencodeiiita/Code-Digger#3]
## Steps to solve this problem successfully
- Solve the problem and create a new file `output.txt` in the same task folder
- Store the output in `output.txt`
- Also attach a file containing your code
- Submit a PR within 1 day
- Your PR will not be merged if it contains Wrong Answer

If you need any help regarding this issue, contact @hdelic#6900 on discord

**Comment by vedant-z** [comment]
@pvtrpndy May I work on this?

**Comment by Himanshu276330** [comment]
Yes, you may.

**Comment by PiyushGG18** [comment]
claim

**Comment by Phantom-Harsh** [comment]
Claim

**Comment by RibhavBansal** [comment]
Claim

**Comment by vedant-z** [comment]
@pvtrpndy Are there any issues? Asking this as you reopened this.

**Comment by Finesse-734** [comment]
claim

**Comment by atulbraj** [comment]
claim
