### ISSUE TITLE
Task 4: Among Sussier

### ISSUE THREAD

**Issue by pvtr03** [opencodeiiita/Code-Digger#35]
## Steps to solve this problem successfully
- Solve the problem and create a new file `output.txt in` the same task folder
- Store the output in `output.txt`
- Also attach a file containing your code
- Submit a PR within 1 day
- Your PR will not be merged if it contains Wrong Answer

If you need any help regarding this issue, contact @hdelic#6900 on discord

**Comment by RibhavBansal** [comment]
claim

**Comment by anshgeez31** [comment]
claim

**Comment by pvtr03** [comment]
Assigned to @RibhavBansal

**Comment by anim2403** [comment]
Claim

**Comment by atulbraj** [comment]
claim

**Comment by Siddhant-Agarwal4583** [comment]
claim
