### ISSUE TITLE
Task 5

### ISSUE THREAD

**Issue by Himanshu276330** [opencodeiiita/Code-Digger#36]
## Steps to solve this problem successfully
- Solve the problem and create a new file `YOURNAME.cpp` or any programming language file in the same task folder
- Store your code in that file
- Submit a PR within 3 day

- This is open for all tasks so you don't need to claim the issue.
- Just submit your pull request.
- After 3 days all the code will be reviewed and the best code concerning time and space complexity will be merged.

If you need any help regarding this issue, contact @Himanshu Shekhar#7026 and  @hdelic#6900 on discord

**Comment by anshgeez31** [comment]
claim

**Comment by terminatorXbgmi** [comment]
Claim

**Comment by Himanshu276330** [comment]
No need to claim, it is open for all read issue descriptions.

**Comment by atulbraj** [comment]
Claim

**Comment by TheDivineAurora** [comment]
sir add testcases please !

**Comment by Himanshu276330** [comment]
@TheDivineAurora 
Think about all the situations and cases by yourself.
If I give more test cases, then you find a pattern, and this question is not so effective.

**Comment by Himanshu276330** [comment]
Make sure your code does not have plagiarism.
If more than two codes have plagiarism, I pick the first code.

Chalo Bhi copy mat Karna 20-point lake job Nahi mileage.

**Comment by Himanshu276330** [comment]
Winner of task5-Jhandu_Bam:
1. [Ishaan23o](https://github.com/opencodeiiita/Code-Digger/issues?q=is%3Apr+author%3AIshaan23o)
2. [vedant-z](https://github.com/opencodeiiita/Code-Digger/issues?q=is%3Apr+author%3Avedant-z)
3. [RibhavBansal](https://github.com/opencodeiiita/Code-Digger/issues?q=is%3Apr+author%3ARibhavBansal)
4. [RayLikesAnime](https://github.com/opencodeiiita/Code-Digger/issues?q=is%3Apr+author%3ARayLikesAnime)
5. [akshatsgh](https://github.com/opencodeiiita/Code-Digger/issues?q=is%3Apr+author%3Aakshatsgh)
