### ISSUE TITLE
Debug 1: nCr modulo m

### ISSUE THREAD

**Issue by pvtr03** [opencodeiiita/Code-Digger#37]
## Steps to solve this problem successfully
- Debug the code and create a new file `code.cpp` the same debug folder
- Store the code in `code.cpp`
- Submit a PR within 1 day
- Your PR will not be merged if it still contains some bugs

If you need any help regarding this issue, contact hdelic#6900 on discord

**Comment by RayLikesAnime** [comment]
claim

**Comment by pvtr03** [comment]
Assigned to @RayLikesAnime

**Comment by akshatsgh** [comment]
claim

**Comment by Siddhant-Agarwal4583** [comment]
claim

**Comment by pvtrpndy** [comment]
What's the progress @RayLikesAnime?

**Comment by pvtr03** [comment]
The issue is open to being claimed.

**Comment by SanyamAgrawal07** [comment]
claim

**Comment by TheDivineAurora** [comment]
claim

**Comment by pvtr03** [comment]
Assigned to @TheDivineAurora

**Comment by RibhavBansal** [comment]
claim

**Comment by pvtr03** [comment]
The issue is up for claims again!

**Comment by KBVijayVarma** [comment]
Claim

**Comment by Siddhant-Agarwal4583** [comment]
Claim

**Comment by pvtr03** [comment]
Assigned to @KBVijayVarma

**Comment by Karansenpai** [comment]
Claim

**Comment by pvtr03** [comment]
@KBVijayVarma how's your progress on the task?

**Comment by KBVijayVarma** [comment]
I could not solve it. Assign it to someone.

**Comment by RibhavBansal** [comment]
Claim

**Comment by Karansenpai** [comment]
Claim

**Comment by Siddhant-Agarwal4583** [comment]
Claim

**Comment by pvtr03** [comment]
Task is open to be claimed now!

**Comment by RibhavBansal** [comment]
Claim

**Comment by pvtr03** [comment]
Assigned to @RibhavBansal
