### ISSUE TITLE
Task 6: Bada badmaash

### ISSUE THREAD

**Issue by pvtr03** [opencodeiiita/Code-Digger#40]
## Steps to solve this problem successfully
- Solve the problem and create a new file `output.txt` in the same task folder
- Store the output in `output.txt`
- Also attach a file containing your code
- Submit a PR within 1 day
- Your PR will not be merged if it contains Wrong Answer

If you need any help regarding this issue, contact @hdelic#6900 on discord

**Comment by vedant-z** [comment]
claim

**Comment by pvtr03** [comment]
Assigned to @vedant-z

**Comment by akshatsgh** [comment]
claim

**Comment by Siddhant-Agarwal4583** [comment]
claim

**Comment by pvtr03** [comment]
@vedant-z what's your progress on this task?

**Comment by RibhavBansal** [comment]
claim

**Comment by Siddhant-Agarwal4583** [comment]
Claim

**Comment by pvtr03** [comment]
This issue is not open for claims yet @RibhavBansal @Siddhant-Agarwal4583

**Comment by pvtrpndy** [comment]
The issue if up for being claimed again!

**Comment by pvtr03** [comment]
The issue is up for being claimed again!

**Comment by GammaMicrowave** [comment]
claim

**Comment by pvtr03** [comment]
Assigned to @GammaMicrowave

**Comment by pvtr03** [comment]
This issue is up for begin claimed again!

**Comment by Siddhant-Agarwal4583** [comment]
Claim

**Comment by pvtr03** [comment]
Assigned to @Siddhant-Agarwal4583

**Comment by Ayashika** [comment]
Claim

**Comment by pvtr03** [comment]
@Siddhant-Agarwal4583 how's your progress on this task?

**Comment by Siddhant-Agarwal4583** [comment]
I am not able to do it. Please assign it to someone else

**Comment by pvtr03** [comment]
Points Increased to 30! and issue is open for claims again!

**Comment by akshatsgh** [comment]
claim

**Comment by pvtr03** [comment]
Assigned to @akshatsgh
