### ISSUE TITLE
Task 7: Among Sussiest

### ISSUE THREAD

**Issue by pvtr03** [opencodeiiita/Code-Digger#57]
## Steps to solve this problem successfully
- Solve the problem and create a new file `output.txt` in the same task folder
- Store the output in `output.txt`
- Also attach a file containing your code
- Submit a PR within 1 day
- Your PR will not be merged if it contains Wrong Answer

If you need any help regarding this issue, contact @hdelic#6900 on discord

**Comment by Aman1143** [comment]
claim

**Comment by pvtr03** [comment]
Assigned to @Aman1143

**Comment by RibhavBansal** [comment]
claim

**Comment by pvtr03** [comment]
Open for claims again!

**Comment by Ishaan23o** [comment]
claim

**Comment by pvtr03** [comment]
Assigned to @Ishaan23o

**Comment by RibhavBansal** [comment]
Claim
