### ISSUE TITLE
Optimize 1: Recursive Function

### ISSUE THREAD

**Issue by pvtr03** [opencodeiiita/Code-Digger#59]
## Steps to solve this problem successfully
- Optimize the code and create a new file `code.cpp` the same optimize folder
- Store the code in `code.cpp`
- Submit a PR within 1 day
- Your PR will not be merged if it still contains some bugs

If you need any help regarding this issue, contact hdelic#6900 on discord

**Comment by RibhavBansal** [comment]
claim

**Comment by TheDivineAurora** [comment]
claim

**Comment by pvtr03** [comment]
Assigned to @RibhavBansal
