### ISSUE TITLE
Design Logo for Codeplus

### ISSUE THREAD

**Issue by pvtr03** [opencodeiiita/Code-Digger#74]
> CodePlus is a group of senior coders at IIIT-A whose aim is to take up coding classes for first-year students and maintain the coding culture at IIIT-A.

- Add your link in the `design.json` file.
- Make sure the visibility of the Figma File is public.
- Note that the issue is _**Open for All**_. There is no need to claim this issue. You can directly submit a PR.

### Note:
- You can add link to any file (Figma or AI etc.) if it can be converted into `svg` file later
- If your logo gets shortlisted, you'll be awarded _**50 points**_
- Deadline for this task is **25 Dec, 11:59pm**

## Party:
- Those whose logo gets selected.

**Comment by anshgeez31** [comment]
claim

**Comment by ananyaa07** [comment]
claim

**Comment by RibhavBansal** [comment]
claim

**Comment by pvtr03** [comment]
This issue is open for all, you don't need to claim it

**Comment by Himanshu276330** [comment]
An additional 50 points will give to the winner if his/her logo is merged with a new Issue Winner.
😌😌

**Comment by Himanshu276330** [comment]
Please see the design issue in the design repo.
