### ISSUE TITLE
Task 9: Binary Search [Freshies only]

### ISSUE THREAD

**Issue by Himanshu276330** [opencodeiiita/Code-Digger#84]
## Steps to solve this problem successfully
- This is for _**First year students**_ only
- Make a programming file in the Implementation folder.
- And implement the binary search for an element.

- Take an array and an element from the user and print `YES` if this element is present in the array or `NO` if not.
- Solve the problem and create a new file `Enrollment_Number.cpp` or any programming file in the same task folder.
- Submit a PR.
- Your PR will not be merged if it gives the Wrong Answer

If you need any help regarding this issue, contact @hdelic#6900 on discord

**Comment by SanyamAgrawal07** [comment]
claim
